"""empty message

Revision ID: 055d371a5044
Revises: 0ef8f1894839
Create Date: 2016-11-18 18:40:28.968882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055d371a5044'
down_revision = '0ef8f1894839'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roll_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['roll_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'roll_id')
    ### end Alembic commands ###
