"""empty message

Revision ID: 0ef8f1894839
Revises: dc60e10806d5
Create Date: 2016-11-18 16:10:55.792598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef8f1894839'
down_revision = 'dc60e10806d5'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    ### end Alembic commands ###
