"""empty message

Revision ID: 84f76650eda1
Revises: 
Create Date: 2016-11-28 17:35:29.522546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f76650eda1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('department_code', sa.String(length=64), nullable=True))
    op.add_column('department', sa.Column('department_description', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'department', ['department_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='unique')
    op.drop_column('department', 'department_description')
    op.drop_column('department', 'department_code')
    ### end Alembic commands ###
