"""empty message

Revision ID: 983d740687d9
Revises: 055d371a5044
Create Date: 2016-11-19 02:42:29.533135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '983d740687d9'
down_revision = '055d371a5044'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'roll_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roll_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(u'user_ibfk_1', 'user', 'role', ['roll_id'], ['id'])
    op.drop_column('user', 'role_id')
    ### end Alembic commands ###
