"""empty message

Revision ID: a82a98c8f3ae
Revises: 983d740687d9
Create Date: 2016-11-27 15:12:46.130317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82a98c8f3ae'
down_revision = '983d740687d9'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('allowed_funcs', sa.Text(), nullable=True))
    op.add_column('role', sa.Column('disallowed_funcs', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'disallowed_funcs')
    op.drop_column('role', 'allowed_funcs')
    ### end Alembic commands ###
